### ISSUE TITLE
Can't find "load image async" node

### ISSUE THREAD

**Issue by chaosdrop** [RaiaN/RuntimeImageLoader#26]
I can only find a "load image sync" node, which loads in sync and causes everything to be loaded in one frame.

![image](https://user-images.githubusercontent.com/3247343/227805163-67da53a0-45c2-4692-89b4-1fe2a0797666.png)

**Comment by RaiaN** [comment]
@chaosdrop What is the engine version? Where did you take the plugin from? Github or Marketplace?

**Comment by chaosdrop** [comment]
Engine is 5.1.1
Github main branch.

Though I did literally just stumble on the fact the Async nodes do appear in the normal blueprint editor, but not the widget blueprint editor where I'm trying to use it.

**Comment by RaiaN** [comment]
You can't use Async nodes in irregular blueprints. Unfortunately, that is the engine limitation.
