### ISSUE TITLE
Runtime GIF loading & decoding support

### ISSUE THREAD

**Issue by RaiaN** [RaiaN/RuntimeImageLoader#28]
Loading GIFs (and webp) is possible at runtime but requires some work around loading and decoding data.

**Comment by aadeshrao123** [comment]
When will you release this broo?

**Comment by RaiaN** [comment]
Absolutely, it is pretty much work in progress and I am aiming to release the update this month! 
What platforms are you interested in?

**Comment by aadeshrao123** [comment]
Windows and Mac

**Comment by RaiaN** [comment]
Windows and Android will be supported. Mac probably not as I don't have the hardware :)

**Comment by RaiaN** [comment]
Feature is ready. Supported Platforms: Windows, Mac, Linux, Android
