### ISSUE TITLE
Feature request - GIF support, animated images

### ISSUE THREAD

**Issue by thecoolwolf** [RaiaN/RuntimeImageLoader#8]
Working on a Vtubing program and the ability to customize things like screens in a room or have animated images attached to your avatar in a packaged project is something I want to add.

**Comment by RaiaN** [comment]
@thecoolwolf Thanks for feedback. I will mark it as a new feature

**Comment by RaiaN** [comment]
Integrate https://github.com/neil3d/UAnimatedTexture4
